# -*- coding: utf-8 -*-
"""Phonebookproject.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ixWALPl7HkqEzWarGvFHchP9VKE-28YP
"""

import pymongo
from pymongo import MongoClient

client = pymongo.MongoClient("mongodb+srv://Harsha123:Harshads17@cluster0.br6du.mongodb.net/myFirstDatabase?retryWrites=true&w=majority")
db = client.Phonebook
notes = db.contacts
display = input("Do you want to display Contacts list? yes/no: ")
if display == 'yes':
  print("Contacts List:")
  for y in notes.find({},{"_id":0, "name": 1, "mobile":1, "Available on Whatsapp":1}).sort('name'):
    print(y)

choice = input("Do you want to add, search or delete contacts?: ")
if choice == 'add':
  n = input("Enter the name: ")
  p = input("Enter the phone number: ")
  w = input("Is this the Whatsapp number? yes/no: ")
  print("Contact is added")
  my_contacts = {'name': n, 'mobile': p, 'Available on Whatsapp': w }
  print(notes.insert_one(my_contacts))
  
if choice == 'search':
  name = input("Enter the name to search: ")
  myquery = {"name": name}
  mydoc = notes.find(myquery,{"_id":0, "name": 1, "mobile":1, "Available on Whatsapp":1})
  for x in mydoc:
    print(x)

if choice == 'delete':
  dname = input("Enter the contact name to delete: ")
  mydquery = {"name": dname}
  x = notes.delete_one(mydquery)
  print(x.deleted_count, "documents deleted.")

Display = input("Do you want to display Contacts list? yes/no: ")
if Display == 'yes':
  print("Contacts List:")
  for y in notes.find({},{"_id":0, "name": 1, "mobile":1, "Available on Whatsapp":1}).sort('name'):
    print(y)